name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore **/*.sln

    - name: Build
      run: dotnet build **/*.sln --configuration Release

    - name: Pack NuGet
      run: |
        latest_version=$(curl -s "https://api.nuget.org/v3-flatcontainer/dotTasker/index.json" | jq -r '.versions[-1]')
        new_version=$(dotnet nuget increment "$latest_version")
        nuspec_path="/nuget/Tasker.nuspec"
        sed -i "s/<version>.*<\/version>/<version>$new_version<\/version>/" "$nuspec_path"
        cat "$nuspec_path"
        dotnet pack -p:NuspecFile="$nuspec_path" -p:PackageVersion="$new_version"
      
  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Push NuGet Package
      run: dotnet nuget push **/*.nupkg --source https://www.nuget.org/api/v3/package --api-key ${{ secrets.NUGET_API_KEY }}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
